# Generated by Django 4.2 on 2023-04-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Введите город', max_length=100, verbose_name='Город')),
                ('street', models.CharField(help_text='Введите улицу', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Введите номер дома', max_length=10, verbose_name='Дом')),
                ('shop_name', models.CharField(help_text='Введите магазин где стоит аппарат', max_length=100, verbose_name='Магазин')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название аппарата')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='vendings.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Аппарат',
                'verbose_name_plural': 'Аппараты',
            },
        ),
        migrations.CreateModel(
            name='CounterWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_value', models.IntegerField(default=0, verbose_name='Значение счетчика')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendings.machine')),
            ],
            options={
                'verbose_name_plural': 'Счетчики выигрышей',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_value', models.IntegerField(verbose_name='Значение счетчика')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='vendings.machine')),
            ],
            options={
                'verbose_name_plural': 'Счетчики',
            },
        ),
    ]
