# Generated by Django 4.2 on 2023-04-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='month',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата снятия счетчика'),
        ),
    ]
