# Generated by Django 4.2 on 2023-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendings', '0003_alter_counter_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edit_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='edit_counter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='edit_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
